import { readFileSync } from 'node:fs';
import { mapHtmlToModel, exportModelToHtml, classifyImageSource, escapeAttribute, addTextObject, addImageObject, deleteObject, createHistory, pushHistory, undo, redo, updateObject } from '../apps/desktop-v2/src/app-v2.mjs';

const fixture = readFileSync('tests/fixtures/v2-simple-slide.html', 'utf8');
const html = readFileSync('apps/desktop-v2/index.html', 'utf8');
const js = readFileSync('apps/desktop-v2/src/app-v2.mjs', 'utf8');
for (const token of ['Open Project','Save Project','Add Text','Undo','Redo','id="canvas"']) if (!html.includes(token)) throw new Error(`missing ${token}`);
let model = mapHtmlToModel(fixture);
if (!model.slides.length || !model.slides[0].objects.length) throw new Error('import model failed');
const firstText = model.slides[0].objects.find((o)=>o.type==='text');
const firstImage = model.slides[0].objects.find((o)=>o.type==='image');
firstText.text = 'X & < >';
updateObject(model, firstImage.id, { x:10, y:20, w:30, h:40 });
const addedText = addTextObject(model, model.currentSlideId); if (!addedText.id) throw new Error('add text failed');
const addedImg = addImageObject(model, model.currentSlideId, 'data:image/png;base64,AA=='); if (!addedImg.src) throw new Error('add image failed');
deleteObject(model, addedText.id);
const hist = createHistory(); pushHistory(hist, model); updateObject(model, firstImage.id, { x:66 }); model = undo(hist, model); model = redo(hist, model);
const exported = exportModelToHtml(model);
if (!exported.includes('X &amp; &lt; &gt;')) throw new Error('escaped text missing');
if (!exported.includes('data:image/png;base64,AA==')) throw new Error('added image missing');
if (exported.includes('https://')) throw new Error('remote url leaked');
if (!mapHtmlToModel('<img src="https://x.com/a.png">').slides[0].objects[0].lockedReason) throw new Error('remote image not blocked');
if (escapeAttribute(`a"b'c&<>`) !== 'a&quot;b&#39;c&amp;&lt;&gt;') throw new Error('attribute escaping failed');
for (const forbidden of ['fetch(', 'XMLHttpRequest', 'WebSocket', 'postMessage', 'contentDocument', 'contentWindow', 'localStorage', 'indexedDB']) if (js.includes(forbidden)) throw new Error(`forbidden: ${forbidden}`);
console.log('v2 checks passed');
